# Generated by Django 2.2.6 on 2019-10-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='token',
            field=models.CharField(default='81293812', max_length=30),
        ),
    ]
