# Generated by Django 2.2.6 on 2019-10-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuatormeasurement',
            name='battery_level',
        ),
        migrations.AddField(
            model_name='modulemeasurement',
            name='battery_level',
            field=models.IntegerField(default=0),
        ),
    ]
